### ISSUE TITLE
Checklist etap 1

### ISSUE THREAD

**Issue by siekaan** [Pevth/Iris_neural_network#1]
- [x] mozliwosc wyboru nauki z biasem lub bez biasu
- [x] zapis calej sieci do pliku
- [x] tryb nauki i tryb testowania
- [x] zapisywanie do pliku globalnego błędu (err*err)

**Comment by siekaan** [comment]
pog
